# Generated by Django 3.1.6 on 2021-03-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='rubbish',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='duty',
            name='water',
            field=models.IntegerField(max_length=20),
        ),
    ]
