# Generated by Django 3.1.6 on 2021-03-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_auto_20210303_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='rubbish',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='duty',
            name='water',
            field=models.IntegerField(),
        ),
    ]
