# Generated by Django 3.1.6 on 2021-03-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('leukocyte', models.CharField(max_length=20)),
                ('platelet', models.CharField(max_length=20)),
                ('neutrophil', models.CharField(max_length=20)),
                ('CA199', models.CharField(max_length=20)),
                ('CA125', models.CharField(max_length=20)),
                ('CEA', models.CharField(max_length=20)),
            ],
        ),
    ]
