# Generated by Django 3.1.6 on 2021-03-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthcheck_ce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='CE',
        ),
    ]
