# Generated by Django 3.1.6 on 2021-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_healthcheck_ce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheck',
            name='date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
