# Generated by Django 3.1.6 on 2021-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20210306_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheck',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='date',
            field=models.DateField(max_length=20),
        ),
    ]
