# Generated by Django 3.1.6 on 2021-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20210306_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheck',
            name='date',
            field=models.DateField(),
        ),
    ]
