# Generated by Django 3.1.6 on 2021-03-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20210306_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheck',
            options={},
        ),
    ]
