# Generated by Django 3.1.6 on 2021-02-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namenumber',
            name='exchange',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
